export const PACKAGES = [
  {
    num: '01',
    tag: 'At our studio',
    title: 'Team Tuft',
    desc: 'Individual mini-rugs. Everyone leaves with a 1×1 ft branded piece they tufted themselves.',
    price: '₹4,500',
    unit: '/ person',
    range: '10–20 people',
    hours: '~3 hrs',
    location: 'Memnagar Studio',
    featured: false,
    color: '#91BA79',
    colorBg: 'rgba(145,186,121,0.08)',
    colorDark: '#5A8B45',
    features: [
      '10 to 20 people',
      '1×1 ft rug per person',
      'Branded stencil pre-loaded',
      'Yarn in your brand colours',
      'Chai, snacks & good vibes',
    ],
    slug: 'team-tuft',
    emoji: '🏠',
    pricePerPerson: 4500,
    minPeople: 10,
    maxPeople: 20,
    isPerPerson: true,
  },
  {
    num: '02',
    tag: 'Most booked',
    title: 'Office Pop-Up',
    desc: "We bring the full setup to your office. Perfect for annual days, founders' week, and large team events.",
    price: '₹5,500',
    unit: '/ person',
    range: '15–50 people',
    hours: '3–4 hrs',
    location: 'Your office',
    featured: true,
    color: '#E1802D',
    colorBg: 'rgba(225,128,45,0.08)',
    colorDark: '#C0631A',
    features: [
      '15 to 50 people',
      'Full transport, setup & cleanup',
      'Individual takeaway rugs',
      'Group photo wall included',
      'Mumbai / Pune on request',
    ],
    slug: 'office-popup',
    emoji: '🏢',
    pricePerPerson: 5500,
    minPeople: 15,
    maxPeople: 50,
    isPerPerson: true,
  },
  {
    num: '03',
    tag: 'The statement piece',
    title: 'Brand Rug',
    desc: 'One large collaborative rug your whole team builds together — permanently displayed in your reception or boardroom.',
    price: '₹65,000',
    unit: ' onwards',
    range: 'Up to 25 people',
    hours: '3 hrs',
    location: 'Studio or office',
    featured: false,
    color: '#36746F',
    colorBg: 'rgba(54,116,111,0.08)',
    colorDark: '#2A5955',
    features: [
      'Collaborative — everyone contributes',
      '3×5 ft or 4×6 ft rug',
      'Custom brand-designed',
      'Mounted & ready to hang',
      '10 working days turnaround',
    ],
    slug: 'brand-rug',
    emoji: '🎨',
    pricePerPerson: 65000,
    minPeople: 1,
    maxPeople: 1,
    isPerPerson: false,
  },
]

export const PACKAGE_DETAILS = {
  'team-tuft': {
    subtitle: 'At our studio',
    totalExample: '₹67,500 for 15 people',
    details:
      'Our Memnagar studio accommodates up to 20 people with individual tufting stations. Each participant receives hands-on guidance from our instructors. The branded stencil — your logo, pattern, or custom design — is pre-loaded onto every frame before your team arrives. After the session, we take the raw pieces back for professional finishing: backing, trimming, and framing. Finished rugs are delivered to your office within 7 working days.',
    detailFeatures: [
      { title: '10 to 20 people', desc: 'Ideal group size for our Memnagar studio' },
      { title: '~3 hours total', desc: '15 min instruction, 2 hrs tufting, wrap-up' },
      { title: '1×1 ft rug per person', desc: 'Branded stencil pre-loaded on every frame' },
      { title: 'Brand colours', desc: 'Yarn matched to your brand palette (60+ shades)' },
      { title: 'Chai & snacks', desc: 'Tea breaks and snacks included in the session' },
      { title: 'Framed & finished', desc: 'Delivered to your office within 7 working days' },
    ],
  },
  'office-popup': {
    subtitle: 'Onsite at your office',
    totalExample: '₹1,37,500 for 25 people',
    badge: 'Most booked',
    details:
      'Our onsite pop-up is our most popular corporate option. We bring everything — tufting frames, guns, yarn in your brand colours, backing cloth, finishing materials, and our instructor team. All you need is a room of roughly 600 sq ft per 20 people, standard power outlets, and flat working surfaces. For groups over 30, we split into waves to keep our instructor-to-participant ratio tight.',
    detailFeatures: [
      { title: '15 to 50 people', desc: 'Scalable setup for any team size' },
      { title: 'Full-service setup', desc: 'We handle transport, setup, and cleanup' },
      { title: 'Individual takeaway rugs', desc: 'Plus a group photo wall for memories' },
      { title: 'Gujarat coverage', desc: 'Ahmedabad, Gandhinagar, GIFT City included' },
      { title: 'Mumbai / Pune available', desc: 'Add travel costs for outstation events' },
      { title: 'Branded experience', desc: 'Custom stencils and brand colour matching' },
    ],
  },
  'brand-rug': {
    subtitle: 'The statement piece',
    totalExample: 'Final quote based on size & design',
    details:
      'The Brand Rug is a statement piece — a single large rug that your entire team builds together. We design the stencil around your brand identity: your logo, tagline, founding date, team values, or a custom pattern. On event day, team members take turns tufting different sections, so every person contributes to the final piece.',
    detailFeatures: [
      { title: 'Up to 25 people', desc: 'Collaborative piece — everyone contributes' },
      { title: '3×5 ft or 4×6 ft', desc: 'Large finished rug for your space' },
      { title: 'Custom brand design', desc: 'Designed around your logo and identity' },
      { title: 'Mounted & delivered', desc: 'Ready to hang on your wall' },
      { title: '10 working days', desc: 'Typical turnaround after the event' },
      { title: 'Premium finishing', desc: 'Professional backing, trimming, and mounting' },
    ],
  },
}

export const COMPARE_ROWS = [
  { label: 'Participants',            vals: ['10–20', '15–50', 'Up to 25'] },
  { label: 'Location',                vals: ['Our studio', 'Your office', 'Studio or office'] },
  { label: 'Individual takeaway rug', vals: ['✓', '✓', '✗ (group piece)'] },
  { label: 'Setup & cleanup',         vals: ['We handle', 'We handle', 'We handle'] },
  { label: 'Turnaround',              vals: ['7 days', '7 days', '10 days'] },
  { label: 'GST invoice',             vals: ['✓', '✓', '✓'] },
]
